### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 0xMenkoh** [ibzann/ibzann#1]
how did u got the github pro badge?

**Comment by tarvar** [comment]
it's actually added to you profile when you subscribe for gh pro retar

**Comment by 0xMenkoh** [comment]
where can I buy it?

**Comment by ibzann** [comment]
https://github.com/settings/billing/plans

**Comment by 0xMenkoh** [comment]
thanks and why did you bought it exactly?

**Comment by ibzann** [comment]
i got it for free

**Comment by 0xMenkoh** [comment]
wtf how

**Comment by ibzann** [comment]
cause im a student

**Comment by 0xMenkoh** [comment]
kk ty
